### ISSUE TITLE
Error during harvestor set-up

### ISSUE THREAD

**Issue by Dibyendu-IITKGP** [galv-team/galv-harvester#13]
**Describe the bug**
As I try to set-up  a new harvester, I got `KeyError: 'id'`

**To Reproduce**
1. galv-harvester setup
2. API url: //galv-backend-stage.fly.dev
3. Enetr your API token

**Expected behavior**
Ask for the harvester file path and then completes the set up.
![harvester_error](https://github.com/user-attachments/assets/3160125c-0941-4111-a5b4-f043ed3d9fcd)

**Comment by mjaquiery** [comment]
This is due to connecting to http rather than https, I think. I've added a check to require that the server sends HTTP 201 ("Created") as a response, rather than just checking it doesn't send an error response (release 1.3.3).
