### ISSUE TITLE
Running through docker - account set up error

### ISSUE THREAD

**Issue by Dibyendu-IITKGP** [galv-team/galv-harvester#14]
**Describe the bug**
Note that this should be a bug in Galv's specification or overall design, not a bug in a specific implementation of Galv.
For bugs in a specific implementation, please open an issue in the relevant repository.
- [Backend](/galv-team/galv-backend/issues/new/choose)
- [Frontend](/galv-team/galv-frontend/issues/new/choose)
- [Harvester](/galv-team/galv-harvester/issues/new/choose)

**To Reproduce**
1. from the Galv directory - `sudo docker-compose up frontend`
2. Go to sign up
3. Fill the details in sign up page
4. Click on register - you'll see error in the terminal

**Expected behavior**
A activation code in the MailHog

**Additional context**
![docker_error](https://github.com/user-attachments/assets/0d2a11d4-9a70-4b17-b038-e3e74d7e3e4b)

**Comment by mjaquiery** [comment]
This is a conflict between `localhost` and `127.0.0.1`. We've updated the `docker-compose.yml` file to make it less likely to occur.
